source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.2'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Fotech: Extra gems not dragged by rails.
gem 'memoizer', '~> 1.0.3'
gem 'cancancan', '~> 2.3.0' # Replacement for old vendor/plugin/declarative_authorization.
gem 'delayed_job', '~> 4.1.5' # Replacement for old vendor/plugin/delayed_job
gem 'delayed_job_active_record', '~> 4.1.3'

# Gems already in installer Gemfile.
gem 'georuby', '~> 2.5.2'
gem 'uuidtools', '~> 2.1.5'
gem 'paper_trail', '~> 10.2.0'
gem 'mini_magick', '~> 4.9.3'
gem 'ffi-rzmq', '~> 2.0.7'
gem 'daemons', '~> 1.3.1'
gem 'i18n-js', '~> 3.2.1'
gem 'minitar', '~> 0.8'

gem 'therubyracer', '~> 0.12.3'
gem 'net-ping', '~> 2.0.5'  # Replacement for ping, last available in ruby 1.8.7.
gem 'pothoven-attachment_fu', '~> 3.3.2' # Replacement for attachment_fu.
