#!/opt/Fotech/common/ruby/bin/ruby

## Daemons sets pwd to /, so we have to explicitly set RAILS_ROOT
#RAILS_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))
#
## Create the PIDS directory if it does not already exist.
#tmpdir = "#{RAILS_ROOT}/tmp/pids"
#if not File.directory?(tmpdir)
#    Dir.mkdir(tmpdir)
#end

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed/command'
Delayed::Command.new(ARGV).daemonize
