# FILENAME:     email.yml
# AUTHOR:       Steven Klassen
# CREATED ON:   2009-12-21
#
# LAST CHANGE:
# $Author: $
#   $Date: $
#    $Rev: $
#    $URL: $
#
# COPYRIGHT:
# This file is Copyright © 2009 Fotech Solutions Ltd. All rights reserved.


production:
  delivery_method: :smtp
  smtp_settings:
    address: smtp.office365.com
    port: 587
    domain: fotechsolutions.com
    authentication: :login
    user_name: techsupport@fotechsolutions.com
    password: Welcome44
    tls: true

development:
  delivery_method: :smtp
  smtp_settings:
    address: smtp.office365.com
    port: 587
    domain: fotechsolutions.com
    authentication: :login
    user_name: techsupport@fotechsolutions.com
    password: Welcome44
    tls: true

test:
  delivery_method: :smtp
  smtp_settings:
    address: smtp.office365.com
    port: 587
    domain: fotechsolutions.com
    authentication: :login
    user_name: techsupport@fotechsolutions.com
    password: Welcome44
    tls: true
