# Default template, used for new configs (same as building_no_resolve)
default_settings:
    recommended: [digging, mechanized_digging]
    counting_width: 20
    decrement_value: -1
    threat_threshold:
        green:
            threshold: 5
        amber:
            threshold: 48
            clearance: 42
            hysteresis: 6
        red:
            threshold: 80
    threat_increment:
        hold:
            threshold: 1
        low:
            threshold: 2
            increment_value: 12
        medium:
            threshold: 12
            increment_value: 24
        top:
            threshold: 24
            increment_value: 40


# Escalates to red immediately, never auto-resolves.
quick_no_resolve:
    counting_width: 50
    decrement_value: -1
    threat_threshold:
        amber:
            threshold: 1
            clearance: 0
            hysteresis: 10
        red:
            threshold: 2
    threat_increment:
        hold:
            threshold: 1
        low:
            threshold: 2
            increment_value: 5
        medium:
            threshold: 3
            increment_value: 5
        top:
            threshold: 4
            increment_value: 5

